# Generated by Django 4.2.11 on 2026-05-06 07:17

import auditlogs.mixins
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import duties.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52428800)])),
                ('checksum', models.CharField(help_text='SHA-256 checksum for deduplication', max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('currently_available', models.BooleanField(default=True)),
            ],
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DutyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
            ],
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('shift', models.CharField(max_length=20)),
                ('employee_name', models.CharField(default='__Missing__', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'employee_name'],
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RosterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='template', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(help_text="Schedule name (e.g., 'Morning Shift', 'Night Duty')", max_length=100)),
                ('shift_type', models.CharField(blank=True, help_text='Type of shift (e.g. Regular, On-Call)', max_length=50, null=True)),
                ('alias', models.CharField(blank=True, help_text='Short code or alias for the shift', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='org.workingoffice')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='rosterassignment',
            constraint=models.UniqueConstraint(fields=('employee_name', 'office', 'start_date', 'end_date', 'start_time', 'end_time', 'shift'), name='uniq_rosterassignment_emp_office_span_times_shift'),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this duty chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited this duty chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_duty_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_charts', to='org.workingoffice'),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='schedules',
            field=models.ManyToManyField(blank=True, help_text='Schedules (shifts) covered by this duty chart.', related_name='duty_charts', to='duties.schedule'),
        ),
        migrations.AddField(
            model_name='duty',
            name='duty_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='duties.dutychart'),
        ),
        migrations.AddField(
            model_name='duty',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='org.workingoffice'),
        ),
        migrations.AddField(
            model_name='duty',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='duties.schedule'),
        ),
        migrations.AddField(
            model_name='duty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('name', 'office', 'start_time', 'end_time'), name='uniq_schedule_name_office_times'),
        ),
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together={('user', 'duty_chart', 'date', 'schedule')},
        ),
    ]
