# Generated by Django 5.2.5 on 2026-02-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
    ]
