# Generated by Django 4.2.11 on 2026-05-06 07:26

from django.db import migrations, models
import duties.models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutychart',
            name='approval_document',
            field=models.FileField(blank=True, null=True, upload_to=duties.models.duty_chart_approval_path),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
