# Generated by Django 5.2.5 on 2026-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_schedule_alias_schedule_shift_type_and_more'),
        ('org', '0003_rename_name_directorate_directorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='org.workingoffice'),
        ),
        migrations.AlterField(
            model_name='dutychart',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_charts', to='org.workingoffice'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='org.workingoffice'),
        ),
    ]
