# Generated by Django 5.2.5 on 2026-03-04 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_alter_duty_office_alter_dutychart_office_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dutychart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this duty chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited this duty chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_duty_charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
