# Generated by Django 4.2.11 on 2026-05-08 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duties', '0003_anusuchidocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutychart',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_duty_charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
