# Generated by Django 4.2.11 on 2026-06-05 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duties', '0004_dutychart_approval_date_dutychart_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutychart',
            name='pool_members',
            field=models.ManyToManyField(blank=True, help_text="Curated standby employees who can be assigned to this chart's days.", related_name='duty_chart_pools', to=settings.AUTH_USER_MODEL),
        ),
    ]
