# Generated by Django 5.2.5 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0004_dutychart_add_audit_fields'),
    ]

    operations = [
    ]
