# Generated by Django 5.2.5 on 2026-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_dutychart_status'),
    ]

    operations = [
    ]
