# Generated by Django 5.2.5 on 2026-05-06 14:55

import duties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0006_alter_dutychart_status'),
    ]

    operations = [
    ]
