# Generated by Django 5.2.5 on 2026-05-06 15:15

import django.db.models.deletion
import duties.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0007_dutychart_approval_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
