# Generated by Django 4.2.11 on 2026-06-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_dutychart_pool_members'),
        ('duties', '0008_anusuchidocument'),
    ]

    operations = [
    ]
