"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")
# Always include loopback addresses so the Docker health check (which hits
# http://127.0.0.1:8000/...) never gets a DisallowedHost rejection.
ALLOWED_HOSTS = list(set(_allowed_hosts + ["localhost", "127.0.0.1"]))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-development')
if not SECRET_KEY or SECRET_KEY == 'django-insecure-default-key-for-development':
    if os.environ.get('DEBUG', 'True') == 'False':
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("SECRET_KEY must be configured as a secure value in production.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

if not DEBUG:
    # Trust X-Forwarded-Proto from the nginx reverse proxy so Django knows the
    # original request was HTTPS and doesn't issue its own 301 redirect loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # nginx at the edge enforces HTTPS; gunicorn is HTTP-only internally
    # Exempt health check + admin from the SSL redirect so the Docker health
    # check (plain HTTP to localhost) doesn't trigger a redirect loop.
    SECURE_REDIRECT_EXEMPT = [r'^admin/', r'^health/']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CORS Configuration
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:8001",
        "http://127.0.0.1:8001",
        "http://localhost:8083",
        "http://127.0.0.1:8083"
    ]
else:
    cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "https://dutychart.ntc.net.np")
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(",")]
    CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-mobile-token',
    'mobile-api-token',
    'x-mobile-session-token',
    'mobile-session-token',
    'x-recaptcha-token',
    'x-firebase-appcheck',
    'cache-control',
    'pragma',
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
    'storages',
    # Local apps
    'users',
    'org',
    'duties',
    'otp_service',
    'auditlogs',
    'channels',
    'notification_service',
    'help_center',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlogs.middleware.AuditContextMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Add your project-level templates dir here (optional if you keep
        # them inside the app folder, but handy if you ever use global templates)
        'DIRS': [
            BASE_DIR / 'templates',  # <- creates a central templates/ folder at project root
        ],

        'APP_DIRS': True,  # <- keep this True so Django finds templates in each app, e.g. duties/templates/

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'
import sys

# Postgres Setup
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', 60)),  # Reuse connections for 60s
        'CONN_HEALTH_CHECKS': True,  # Auto-reconnect stale persistent connections
    }
}

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# AWS S3 Settings
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
AWS_S3_VERIFY = os.getenv('AWS_S3_VERIFY', 'False') == 'True'
AWS_S3_CLOCK_SKEW = int(os.getenv('AWS_S3_CLOCK_SKEW', 0))
AWS_S3_USE_SSL = os.getenv('AWS_S3_USE_SSL', 'True') == 'True'
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'garage')
AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'path')
AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION', 's3v4')
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = os.getenv('AWS_QUERYSTRING_AUTH', 'False') == 'True'
AWS_S3_FILE_OVERWRITE = os.getenv('AWS_S3_FILE_OVERWRITE', 'False') == 'True'

# Media files
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# NTC OTP Settings
NTC_OTP_URL = os.environ.get('NTC_OTP_URL')

# NTC SMS Settings
NTC_SMS_URL = os.environ.get('NTC_SMS_URL', 'http://10.26.192.122:42399/updatedsmssender-1.0-SNAPSHOT/updatedsmssender/')
NTC_SMS_USERNAME = os.environ.get('NTC_SMS_USERNAME', 'NtcSmsSender')
NTC_SMS_PASSWORD = os.environ.get('NTC_SMS_PASSWORD', '')
NTC_SMS_SYSTEM_ID = os.environ.get('NTC_SMS_SYSTEM_ID', '1')

# Mobile API Token
MOBILE_API_TOKEN = os.environ.get('MOBILE_API_TOKEN')

# Image Version from env
IMAGE_VERSION = os.environ.get('IMAGE_VERSION', 'v1.0.0-dev')

# Google reCAPTCHA v3
# Leave unset (or empty) to disable reCAPTCHA checks (development).
# In production set RECAPTCHA_SECRET_KEY to the server-side secret from
# https://www.google.com/recaptcha/admin and pass RECAPTCHA_SITE_KEY to the frontend.
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '')

# Firebase App Check (Play Integrity / DeviceCheck)
# Set to the numeric Project Number from Firebase Console → Project Settings → General.
# When set, POST /api/v1/mobile/auth/ requires an X-Firebase-AppCheck token instead of
# the static MOBILE_API_TOKEN, defeating APK reverse-engineering attacks.
# Leave unset to fall back to static token (development / pre-AppCheck migration).
FIREBASE_PROJECT_NUMBER = os.environ.get('FIREBASE_PROJECT_NUMBER', '')

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",  # only JSON
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "authentication.permissions.IsAuthenticatedOrHasMobileToken",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "200/minute" if DEBUG else "20/minute",
        "user": "1000/minute" if DEBUG else "100/minute",
    }
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': None,
    'JTI_CLAIM': 'jti',
}
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "JWT Authorization header using the Bearer scheme. Example: 'Bearer <token>'",
        }
    },
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Swagger / DRF login fix
LOGIN_URL = '/api-auth/login/'
LOGOUT_URL = '/api-auth/logout/'

# Django Channels Configuration
ASGI_APPLICATION = 'config.asgi.application'

if os.getenv('USE_INMEMORY_CHANNEL_LAYER') == 'True' or not os.getenv('REDIS_HOST'):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), 6379)],
            },
        },
    }

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f"redis://{os.environ.get('REDIS_HOST', '127.0.0.1')}:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TIMEZONE = 'Asia/Kathmandu'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'send-duty-reminders-every-1-minute': {
        'task': 'notification_service.tasks.send_duty_reminders',
        'schedule': crontab(minute='*'),  # Every 1 minute
    },
    'send-daily-duty-reminders-every-1-minute': {
        'task': 'notification_service.tasks.send_daily_duty_reminders',
        'schedule': crontab(minute='*'),  # Every 1 minute
    },
}
