# Generated by Django 5.2.5 on 2026-02-03 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_name', models.CharField(blank=True, help_text='Snapshot of username/email', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('entity_type', models.CharField(help_text='Model name (e.g. Duty, User)', max_length=100)),
                ('entity_id', models.CharField(help_text='ID of the modified record', max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='auditlogs_a_entity__c9c27f_idx'), models.Index(fields=['action'], name='auditlogs_a_action_b1f2ec_idx'), models.Index(fields=['actor'], name='auditlogs_a_actor_i_0ee617_idx')],
            },
        ),
    ]
