# Generated by Django 5.2.5 on 2026-02-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0002_auditlog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_employee_id',
            field=models.CharField(blank=True, help_text='Snapshot of employee ID', max_length=100, null=True),
        ),
    ]
