# Generated by Django 5.2.5 on 2026-02-03 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0003_auditlog_actor_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlogs_a_entity__c9c27f_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_userid',
            field=models.CharField(blank=True, help_text="Snapshot of user's username/ID", max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type'], name='auditlogs_a_entity__ce66ef_idx'),
        ),
    ]
