# Generated by Django 4.2.11 on 2026-05-08 05:03

import auditlogs.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='account_office_name', max_length=255)),
            ],
            options={
                'db_table': 'ac_offices',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CCOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cc_office_name', max_length=255)),
                ('accounting_office', models.ForeignKey(db_column='account_office_id', on_delete=django.db.models.deletion.CASCADE, related_name='cc_offices', to='org.accountingoffice')),
            ],
            options={
                'db_table': 'cc_offices',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate', models.CharField(max_length=255)),
                ('hierarchy_level', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_directorates', to='org.directorate')),
            ],
            options={
                'db_table': 'directorate',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'holiday',
                'ordering': ['date'],
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=60)),
                ('auto_logout_idle', models.BooleanField(default=True)),
                ('latest_app_version', models.CharField(default='1.0.0', max_length=20)),
                ('old_app_version', models.CharField(default='1.0.0', max_length=20)),
                ('app_update_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name_of_office', max_length=255)),
                ('ac_office', models.ForeignKey(blank=True, db_column='ac_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.accountingoffice')),
                ('cc_office', models.ForeignKey(blank=True, db_column='cc_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.ccoffice')),
                ('directorate', models.ForeignKey(blank=True, db_column='directorate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.directorate')),
            ],
            options={
                'db_table': 'working_office',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='org.department')),
            ],
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='department',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='org.directorate'),
        ),
        migrations.AddField(
            model_name='accountingoffice',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_offices', to='org.directorate'),
        ),
    ]
