# Generated by Django 4.2.11 on 2026-05-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
