# Generated by Django 4.2.11 on 2026-05-08 05:15

import auditlogs.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_delete_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'holiday',
                'ordering': ['date'],
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
    ]
