# Generated by Django 4.2.11 on 2026-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='show_sunday_as_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
