# Generated by Django 5.2.5 on 2026-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_systemsetting_app_update_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsetting',
            old_name='min_app_version',
            new_name='old_app_version',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='app_update_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
