# Generated by Django 4.2.11 on 2026-06-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_systemsetting_show_sunday_as_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingoffice',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_offices', to='org.workingoffice'),
        ),
    ]
