# Generated by Django 4.2.11 on 2026-06-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_workingoffice_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingoffice',
            options={'ordering': ['id']},
        ),
    ]
