# Generated by Django 5.2.5 on 2026-02-01 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(choices=[('sms_ntc', 'NTC SMS'), ('email', 'Email')], max_length=20)),
                ('seq_no', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('purpose', models.CharField(choices=[('forgot_password', 'Forgot Password'), ('change_password', 'Change Password')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
