# Generated by Django 5.2.5 on 2026-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='purpose',
            field=models.CharField(choices=[('forgot_password', 'Forgot Password'), ('change_password', 'Change Password'), ('signup', 'Signup'), ('login_2fa', 'Login 2FA')], max_length=32),
        ),
    ]
