# Generated by Django 5.2.5 on 2026-02-16 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_alter_duty_office_alter_dutychart_office_and_more'),
        ('notification_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs_for_duty', to='duties.duty'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='reminder_type',
            field=models.CharField(default='GENERAL', help_text='Type of reminder (e.g., 1_HOUR, DAILY, ASSIGNMENT)', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='smslog',
            constraint=models.UniqueConstraint(fields=('user', 'duty', 'reminder_type'), name='unique_sms_reminder_per_duty'),
        ),
    ]
