# Generated by Django 4.2.11 on 2026-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='smslog',
                    name='reminder_type',
                    field=models.CharField(default='GENERAL', help_text='Type of reminder (e.g., 1_HOUR, DAILY, ASSIGNMENT)', max_length=50),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='smslog',
            constraint=models.UniqueConstraint(fields=('user', 'duty', 'reminder_type'), name='unique_sms_reminder_per_duty'),
        ),
    ]
