# Generated by Django 4.2.11 on 2026-06-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_smslog_duty_smslog_reminder_type_and_more'),
        ('notification_service', '0002_smslog_reminder_type_and_more'),
    ]

    operations = [
    ]
