# Generated by Django 4.2.11 on 2026-06-11 10:13

import auditlogs.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_alter_workingoffice_options'),
        ('notification_service', '0003_merge_20260611_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_advance_reminder', models.BooleanField(default=True)),
                ('advance_reminder_minutes', models.IntegerField(default=60)),
                ('advance_reminder_template', models.TextField(blank=True, null=True)),
                ('enable_daily_reminder', models.BooleanField(default=True)),
                ('daily_reminder_time', models.TimeField(default='10:00:00')),
                ('daily_reminder_template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='org.workingoffice')),
            ],
            options={
                'db_table': 'office_notification_setting',
                'ordering': ['id'],
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
    ]
