# Generated by Django 4.2.11 on 2026-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0004_officenotificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officenotificationsetting',
            name='advance_reminder_minutes',
        ),
        migrations.RemoveField(
            model_name='officenotificationsetting',
            name='daily_reminder_template',
        ),
        migrations.RemoveField(
            model_name='officenotificationsetting',
            name='daily_reminder_time',
        ),
        migrations.RemoveField(
            model_name='officenotificationsetting',
            name='enable_daily_reminder',
        ),
        migrations.AddField(
            model_name='officenotificationsetting',
            name='advance_reminder_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='officenotificationsetting',
            name='allowed_duty_charts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officenotificationsetting',
            name='allowed_shifts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
