# Generated by Django 4.2.11 on 2026-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0005_remove_officenotificationsetting_advance_reminder_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officenotificationsetting',
            name='advance_reminder_days',
            field=models.IntegerField(default=1),
        ),
    ]
