# Generated by Django 4.2.11 on 2026-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0006_officenotificationsetting_advance_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='officenotificationsetting',
            name='schedule_configs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
