# Generated by Django 4.2.11 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0007_officenotificationsetting_schedule_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Duty Assignment'), ('REMINDER', 'Duty Reminder'), ('SYSTEM', 'System Alert'), ('DOCUMENT', 'Document Upload')], default='SYSTEM', max_length=20),
        ),
    ]
