# Generated by Django 5.2.5 on 2026-02-06 14:44

import auditlogs.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_systemsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorate',
            old_name='name',
            new_name='directorate',
        ),
        migrations.AddField(
            model_name='directorate',
            name='hierarchy_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='directorate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_directorates', to='org.directorate'),
        ),
        migrations.AddField(
            model_name='directorate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='directorate',
            table='directorate',
        ),
        migrations.CreateModel(
            name='AccountingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='account_office_name', max_length=255)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_offices', to='org.directorate')),
            ],
            options={
                'db_table': 'ac_offices',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CCOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cc_office_name', max_length=255)),
                ('accounting_office', models.ForeignKey(db_column='account_office_id', on_delete=django.db.models.deletion.CASCADE, related_name='cc_offices', to='org.accountingoffice')),
            ],
            options={
                'db_table': 'cc_offices',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name_of_office', max_length=255)),
                ('ac_office', models.ForeignKey(blank=True, db_column='ac_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.accountingoffice')),
                ('cc_office', models.ForeignKey(blank=True, db_column='cc_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.ccoffice')),
                ('directorate', models.ForeignKey(blank=True, db_column='directorate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.directorate')),
            ],
            options={
                'db_table': 'working_office',
            },
            bases=(auditlogs.mixins.AuditableMixin, models.Model),
        ),
    ]
