# Generated by Django 5.2.5 on 2026-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_rename_name_directorate_directorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='app_update_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='latest_app_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='min_app_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
