# Generated by Django 4.2.11 on 2026-06-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_rename_min_app_version_systemsetting_old_app_version_and_more'),
        ('org', '0005_workingoffice_parent'),
    ]

    operations = [
    ]
