# Generated by Django 5.2.5 on 2026-02-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
    ]
