# Generated by Django 4.2.11 on 2026-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='responsibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
