# Generated by Django 5.2.5 on 2026-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_rename_name_directorate_directorate_and_more'),
        ('users', '0003_user_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='org.workingoffice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_offices',
            field=models.ManyToManyField(blank=True, help_text='Other offices this user belongs to (secondary memberships).', related_name='secondary_members', to='org.workingoffice'),
        ),
        migrations.AlterField(
            model_name='userdashboardoffice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_users', to='org.workingoffice'),
        ),
    ]
