# Generated by Django 5.2.5 on 2026-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('users', '0003_user_is_activated'),
    ]

    operations = [
    ]
