# Generated by Django 4.2.11 on 2026-03-03 05:50

from django.db import migrations

def seed_responsibilities(apps, schema_editor):
    UserResponsibility = apps.get_model('users', 'UserResponsibility')
    responsibilities = [
        "Optical Fiber",
        "Optical System",
        "Satellite System",
        "Microwave Radio System",
        "Power System",
        "Admin/ Store",
        "Vehicles",
        "System Monitoring",
        "Filed Team",
        "Transmission",
        "Optical Team",
        "RF"
    ]
    for r in responsibilities:
        UserResponsibility.objects.get_or_create(name=r)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userresponsibility_alter_user_responsibility'),
    ]

    operations = [
        migrations.RunPython(seed_responsibilities),
    ]
