# Generated by Django 5.2.5 on 2026-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_position_alias_alter_user_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardoffice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
