# Generated by Django 4.2.11 on 2026-06-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20260303_1135'),
        ('users', '0005_userdashboardoffice_order'),
    ]

    operations = [
    ]
